before_install:
  - gem update bundler
before_script:
  - bundle exec rake setup
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate
env:
  DATABASE_URL: postgres://postgres@localhost/travis_ci_test
language: ruby
addons:
  postgresql: "9.3"
notifications:
  email: false
rvm:
  - 2.3.8
  - 2.7.2
