postgres:
  image: postgres:9.6
  environment:
    - POSTGRES_PASSWORD=dev
  ports:
    - "5432"

web:
  build: .
  command: ["bundle", "exec", "rackup", "-p", "80", "-o", "0.0.0.0", "config.ru"]
  environment:
    - "WATERMARK_DEV_ENV_DOMAIN"
    - "DATABASE_URL=postgres://postgres:dev@db/tessa_development"

  volumes:
    - .:/app
    - ../../gems:/wcc-gems
    - tessa_bundle:/bundle
  ports:
    - "3111:80"
  links:
    - postgres:db
