postgres:
  image: postgres
  ports:
    - "5432"

web:
  build: .
  command: ["rackup", "-p", "80", "-o", "0.0.0.0", "config.ru"]
  environment:
    - "WATERMARK_DEV_ENV_DOMAIN"
    - "DATABASE_URL=postgres://postgres@db/tessa_development"

  volumes:
    - .:/app
    - ../../gems:/wcc-gems
  ports:
    - "3111:80"
  links:
    - postgres:db

