version: "3.7"
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=dev
    ports:
      - "5432"

  web:
    build: .
    command: ["bundle", "exec", "rackup", "-p", "80", "-o", "0.0.0.0", "config.ru"]
    environment:
      - "WATERMARK_DEV_ENV_DOMAIN"

    volumes:
      - .:/app:delegated
      - bundle:/bundle:cached
    ports:
      - "3111:80"
    depends_on:
      - postgres

volumes:
  bundle:
